// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CelestesFavouriteMusicians.Migrations
{
    [DbContext(typeof(CelestesFavouriteMusiciansContext))]
    partial class CelestesFavouriteMusiciansContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("CelestesFavouriteMusicians.Models.Musicians", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfAlbums")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfAwards")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Musicians");
                });
#pragma warning restore 612, 618
        }
    }
}
